### ISSUE TITLE
flash encryption for esp32fota for esp32-wroom-32e

### ISSUE THREAD

**Issue by simogaspa84** [chrisjoyce911/esp32FOTA#104]
Hi @chrisjoyce911 ..

I am wondering if you have some future plans to add the encryption of flash/spiff for secure store the information about the connection with the server and the keys for the signature of the fw.

Thanks a lot for your time

**Comment by tobozo** [comment]
Hi,

I guess industrialization of this library isn't planned, the scope is purely educational anyway.

For any serious security, it is strongly recommended to use built-in security provided by esp-idf and a reliable ethernet module.

Closing this as wontfix.
