### ISSUE TITLE
what if i reset mcu?

### ISSUE THREAD

**Issue by KJPOUNDY132** [chrisjoyce911/esp32FOTA#112]
hi if we reset mcu, last updated firmware runs from storage? or gets firmware on evey boot

**Comment by Humancell** [comment]
Yes.  If you reset the ESP32 the last loaded firmware will run.

You ESP32 will only check or fetch code on each boot if you wrote that into your code.

**Comment by KJPOUNDY132** [comment]
thank  u very much
