### ISSUE TITLE
Cannot call setProgressCb

### ISSUE THREAD

**Issue by grunnels** [chrisjoyce911/esp32FOTA#123]
Maybe I'm missing something, but cannot call setProgressCb and I don't see it in the source code.  Is it in an upcoming release?

**Comment by tobozo** [comment]
it's a callback setter, it accepts either a lambda function:

```cpp
void setup()
{
  // (...)
  FOTA.setProgressCb( [](size_t progress, size_t size) {
      if( progress == size || progress == 0 ) Serial.println();
      Serial.print(".");
  });
}
```

... or an existing function


```cpp
void my_progress_cb(size_t progress, size_t size) 
{
  if( progress == size || progress == 0 ) Serial.println();
  Serial.print(".");
}

void setup()
{
  // (...)
  FOTA.setProgressCb( my_progress_cb );
}

```

**Comment by grunnels** [comment]
Thanks for the quick reply.  I'm sorry, it was a version mismatch error.  Great library, thanks for the work.
