### ISSUE TITLE
Allow https with redirects

### ISSUE THREAD

**Issue by Panometric** [chrisjoyce911/esp32FOTA#13]
I tried using this library with github as a repo. But it always reports !=200 return codes because all githib https link hit a redirect 301 to https. In this day and age, https is essentially a given.

**Comment by szundi** [comment]
@Panometric Hello Mike, would you like to contribute this as a PR? There is some code that you can use as a reference. We would really appreciate it! :)
https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino

**Comment by chrisjoyce911** [comment]
HTTPClient should handle redirects (http and https) out of the box , but need's to be tested
