### ISSUE TITLE
Allowing the user to select from multiple firmware versions

### ISSUE THREAD

**Issue by HankLloydRight** [chrisjoyce911/esp32FOTA#134]
Hello,
  Right now I'm using the AutoConnect library for OTA updates which is a great lib, but I think has a lot more features than I need so I want to pair it down a little. 

One thing it does is allows the user to select from a list of posted firmware files hosted on the webserver. He includes a Python script to run on the server that reads the *.bin files in a directory and  then generates the required JSON file for the code running on the ESP32, and then presents a list of firmware files in the local web server to the user to select one of them, and then the update begins.

Has anyone done anything like that for esp32FOTA? 

Thanks.

**Comment by tobozo** [comment]
hi,

esp32FOTA updates from manifest are forward-only by definition

implementing a user choice is more of a "launcher" feature, so it would need to be implemented separately with an esp32FOTA instance that doesn't use the manifest file
