### ISSUE TITLE
firmware & file system update from Url fail

### ISSUE THREAD

**Issue by robertobuti** [chrisjoyce911/esp32FOTA#135]
Hello,
i have used the code to update both firmware and file system from url, if just firmware it's ok, if both it fail... , i'm not an expert but i try to debug the problem and seem this case is not provided in the JSON parser function. (i use .gz files but is not relevant)
So in esp32FOTA.cpp around lines 750 i change as follow:

```cpp

    if( has_url ) { // Basic scenario: a complete URL was provided in the JSON manifest, all other keys will be ignored
        _firmwareUrl = doc["url"].as<const char*>(); 
//          Serial.print("FW url : ");  // parser corretto
//          Serial.println(_firmwareUrl);  
        if( has_filesystem ) { // 21/09/23 added url x FS -- Roberto
          _flashFileSystemUrl = protocol + "://" + doc["host"].as<const char*>()+ flashFSPath;
//          Serial.print("FS url : "); // parser corretto
//          Serial.println(_flashFileSystemUrl);
        }

```

in this way the url path for FS is correctly saved and managed. However during FS update it fail for security reason, but i'm using no securty function, also this case seem not provided in FS update, i try to use security certificate but i'm unable to make it, so i solved forcing the FS update without certificate, it work. Next time i will try again to use certificate, for this could be useful and example for non expert like me.
thank.
r.

**Comment by tobozo** [comment]
hi,

you can bypass this by not setting `url` key in the manifest, and instead setting `bin`/`host`/`port` (see the [example manifest](https://github.com/chrisjoyce911/esp32FOTA/blob/master/fota/firmware.json)) keys **and also the `spiffs` key**, this will enable the `has_filesystem` flag and fix the missing protocol/host inheritance

closing this as not an issue, feel free to add followup if you have any question
