### ISSUE TITLE
Can we see percent in order a . ?

### ISSUE THREAD

**Issue by Atorcha** [chrisjoyce911/esp32FOTA#140]
I think It is a better presentation, I suppose only.

What I mean is while it is downloading show the % to full download.

Thanks again

**Comment by tobozo** [comment]
hi,

just use `esp32FOTA.setProgressCb( myProgressFunction )`, your progress function should have the same signature as this: 

```cpp

void myProgressFunction(size_t progress, size_t size)
{
  Serial.printf("Progress: %d / %d\n", progress, size );
}

```
