### ISSUE TITLE
Preserving  variables saved by EEPROM.writeDouble while upgrading

### ISSUE THREAD

**Issue by TBKRK** [chrisjoyce911/esp32FOTA#142]
Arduino board: esp32

Arduino IDE version (found in Arduino -> About Arduino menu): 1.8.19

Hello, I still use version 1.1 of this library (I know... I should upgrade).
Please let me know if upgrading code by this library (or later) will preserve the values of variables saved by EEPROM.writeDouble? I think sometimes after upgrading some of saved variables have different values.

Regards Tomasz

**Comment by tobozo** [comment]
hi,

usually OTA updates don't affect the NVS partition, but you should backup your EEPROM values just in case
