### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by astorun** [chrisjoyce911/esp32FOTA#143]
It is an amazing library to setup a OTA firmware updates..

However, there is no update for more than a year and I would like to see more features in it, such as support of cloudflare HTTPS certificate support etc.

**Comment by JustinTrvz** [comment]
The library is not abandoned. [Last pull request](https://github.com/chrisjoyce911/esp32FOTA/commit/23489cad505c3927f5ee4aa97d7ad2feb16f7a8f) is 3 months ago.

Please create seperate feature requests for your concerns.
