### ISSUE TITLE
update littleFS.bin with this  library ?

### ISSUE THREAD

**Issue by HoseinShirani** [chrisjoyce911/esp32FOTA#147]
Hello and don't be tired 
Thank you very much for your good library.
Can I update part littleFS.bin to FOta through this library?

**Comment by tobozo** [comment]
hi,

just add a `littlefs` entry with the partition binary name to the [json manifest](https://github.com/chrisjoyce911/esp32FOTA/blob/master/fota/firmware.json). 

Obviously you can't store the certificate on the littlefs partition you're updating and the binary size must match the partition size.

**Comment by HoseinShirani** [comment]
Ok thanks, with which examples can I do this

**Comment by tobozo** [comment]
all of them except the one that uses LittleFS to store certificates
