### ISSUE TITLE
What to put in URL

### ISSUE THREAD

**Issue by Nakul93** [chrisjoyce911/esp32FOTA#16]
Hello,
What should I put in place of URL my ip addr?
Because I tried to put that and I am getting error of HTTP

**Comment by chrisjoyce911** [comment]
first thing to check is the URL used to retrieve the json data.

```esp32FOTA.checkURL = "http://server/fota/fota.json"```

Check this URL using curl/wget or a browser on the same wifi network as your esp32.

If this works ok then check the reply .
 for example 
```
{
    "type": "esp32-fota-http",
    "version": 2,
    "host": "192.168.0.100",
    "port": 80,
    "bin": "/fota/esp32-fota-http-2.bin"
}
```

you should then check if you can access the bin image , for this example

```http://192.168.0.100/fota/esp32-fota-http-2.bin```
