### ISSUE TITLE
Return type for forceUpdate is wrong

### ISSUE THREAD

**Issue by davemclaughlin** [chrisjoyce911/esp32FOTA#18]
The return type is bool but the function is declared as string.

Arduino probably doesn't complain as I have not tried this with the Arduino IDE but Visual GDB with Visual Studio and Intellisense won't build this. Returning an empty string works.

**Comment by chrisjoyce911** [comment]
Could you please test a fix on on the branch 'issue18' please

**Comment by davemclaughlin** [comment]
Sorry, late reply. That fix works.

**Comment by chrisjoyce911** [comment]
Fix merged to master
