### ISSUE TITLE
Factory reset functionality

### ISSUE THREAD

**Issue by sujeendran** [chrisjoyce911/esp32FOTA#21]
Hi, 
Is there a factory reset functionality using CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE option within this library? It would be good addition. I work with PlatformIO and am not sure how this option can be enabled with diagnostics GPIO pin configured.
Reference: https://github.com/espressif/esp-idf/tree/600d542f5/examples/system/ota#support-rollback

**Comment by tobozo** [comment]
hi,

sorry about the late response :blush: 

factory reset and rollback aren't part of esp32FOTA scope, but you can easily implement those from your sketch:

just set the second argument of `execOTA( int partition, bool restart_after = true )` to `false` and collect the return value (true=success, false=fail)
 -> on success you can call `ESP.restart()` or your own implementation of `loadFactoryPartition()`
 -> on fail you can do nothing, or `Update.rollBack()` or even `loadFactoryPartition()`
