### ISSUE TITLE
Error: control reaches end of non-void function

### ISSUE THREAD

**Issue by ipqate** [chrisjoyce911/esp32FOTA#3]
Hi,

ARDUINO IDE: 1.8.8
BOARD: ESP32
CODE: AS PER EXAMPLE PROVIDED

I'm trying to run the example but when compiling, I get this error message:

**C:\Users\PCIP\Documents\Arduino\libraries\esp32FOTA\src\esp32fota.cpp: In member function 'bool esp32FOTA::execHTTPcheck()':

C:\Users\PCIP\Documents\Arduino\libraries\esp32FOTA\src\esp32fota.cpp:257:1: error: control reaches end of non-void function [-Werror=return-type]

 }

 ^

Any idea?

**Comment by ipqate** [comment]
Solved! It is a problem when reaching the end of the function without giving back the result, in this case a boolean. Just add RETURN FALSE in the line no. 258.

Please check it:)

**Comment by rljonesau** [comment]
Yes, I had the same issue, but no compiler warning.

In my instance execHTTPcheck does not return an explicit false when the "Is connected" test fails.
I was using AP only mode yet it said there was new firmware on the www server - um no not with AP only mode!

**Comment by szundi** [comment]
this is fixed and merged now
