### ISSUE TITLE
Heap leak when file is not found

### ISSUE THREAD

**Issue by scubachristopher** [chrisjoyce911/esp32FOTA#36]
Hi.

If you pass a file that does NOT exist on the server, you leak the client.  The fix is trivial:

...
            // Check if the HTTP Response is 200
            // else break and Exit Update
            if (line.startsWith("HTTP/1.1"))
            {
                if (line.indexOf("200") < 0)
                {
                    Serial.println("Got a non 200 status code from server. Exiting OTA Update.");
                    **client.stop();**            // THIS NEEDS TO BE ADDED.
                    break;
                }
                gotHTTPStatus = true;
            }
...

I've tested.

Please fix and thanks!

**Comment by BarthV** [comment]
fixed by 27e7cbc582e4e94859862557177a00edd67311b8 ?
