### ISSUE TITLE
lan8720

### ISSUE THREAD

**Issue by workpage2** [chrisjoyce911/esp32FOTA#39]
I tested your library and it works fine with wifi. But doesn't work with lan8720 (ethernet).
Lan8720 uses wifi.h too and I don't understand why it doesn't work.

    bool updatedNeeded = esp32FOTA.execHTTPcheck();
return 0

**Comment by workpage2** [comment]
I found what the problem is. In the library, you use:

    if ((WiFi.status() == WL_CONNECTED))
You can't do that. Because only wifi will work.

**Comment by IoTThinks** [comment]
Nice discovery.
May be need to put in more code if using LAN.
