### ISSUE TITLE
Protected esp32 update

### ISSUE THREAD

**Issue by workpage2** [chrisjoyce911/esp32FOTA#40]
I have tested my program in development mode. Everything worked well. The update worked.
However, after encoding, esp32 refuses to update.
I coded according to this instruction: https://github.com/espressif/arduino-esp32/issues/1387 I pre-encode the firmware file, of course. Any thoughts.

    Fetching Bin: /fw.bin
    Got 1177456 bytes from server
    Got application/octet-stream payload.
    contentLength : 1177456, isValidContentType : 1
    Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while.. 
    Patience!
    Written only : 0/1177456. Retry?
    Error Occurred. Error #: 8

**Comment by WebDust21** [comment]
Pre-encode the firmware file??  Huh?  Unless you're de-encoding the firmware file before feeding it into the update routine, that won't work.
See answer on the other thread.  ESP32 update library uses instructions that specifically do not support encrypted ESP32 FLASH.  Why, I have absolutely no idea.
