### ISSUE TITLE
SPIFFS update

### ISSUE THREAD

**Issue by garageeks** [chrisjoyce911/esp32FOTA#46]
It would be useful to add SPIFFS update option. Ideally it should be made right after the main FOTA update, before rebooting. This is because updating SPIFFS won't result into a FW_VERSION change, therefore it will be stuck in a catch 22 until the SPIFFS binary is deleted from server.

I tried to make this modification but it is not enough. The good thing is that the underlying ESP32 OTA function support SPIFFS update, it just needs a flag.

```
  // check contentLength and content type
    if (contentLength && isValidContentType)
    {
        // Check if there is enough to OTA Update
		if(spiffsFlag) {
			canBegin = Update.begin(contentLength,true);
		} else {
			canBegin = Update.begin(contentLength);
		}			

        // If yes, begin
        if (canBegin)
        {
			if(spiffsFlag) {
				Serial.println("Begin SPIFFS OTA...");
			} else {
				Serial.println("Begin FW OTA...");
			}	
```

**Comment by tobozo** [comment]
see #/47
