### ISSUE TITLE
LITTLEFS Support

### ISSUE THREAD

**Issue by johnkelton** [chrisjoyce911/esp32FOTA#60]
Hi, First of all, thanks for doing such a great job on the library. It worked for me on the first attempt. Just need help with getting LITTLEFS working. Do you have an example I can follow? Thanks in advance. I am in great need of getting LITTLEFS working. :-)

https://github.com/chrisjoyce911/esp32FOTA/pull/47

**Comment by chrisjoyce911** [comment]
You could try an upcoming patch https://github.com/chrisjoyce911/esp32FOTA/pull/79
