### ISSUE TITLE
Esp32 will compile two bin files, one is app and the other is bootstrap. How to upgrade the two files via OTA?

### ISSUE THREAD

**Issue by qutaojiao** [chrisjoyce911/esp32FOTA#63]
Esp32 will compile two bin files, one is app and the other is bootstrap. How to upgrade the two files via OTA?

ESP32-CAM_Motionino.bin 
ESP32-CAM_Motion.ino.partitions.bin

![image](https://user-images.githubusercontent.com/19362820/142787661-397e7665-bd1e-4b53-9cc0-863d15c153c3.png)

**Comment by hpsaturn** [comment]
you only need this extra binary files for the base firmware, after the first flash you only need the main binary. In your example you only need to upload `ESP32-CAM_Motion.ino.partitions.bin` to your server, partitions not.

**Comment by qutaojiao** [comment]
> 您只需要基本固件的额外二进制文件，在第一次闪存后，您只需要主二进制文件。在你的例子中，你只需要上传`ESP32-CAM_Motion.ino.partitions.bin`到你的服务器，分区不需要。

I see. Thank you very much!

**Comment by marcelstoer** [comment]
@hpsaturn isn't your answer inconsistent?

> you only need the main binary. 

Correct.

> In your example you only need to upload `ESP32-CAM_Motion.ino.partitions.bin` to your server, partitions not.

"partitions not" is correct but the file you mentioned actually _is_ the partitions binary, isn't it. Didn't you mean to write `ESP32-CAM_Motion.ino.bin`? People working with PlatformIO would find a `firmware.bin` in the `<project>/.pio/build/<env>` folder (that also contains a `partitions.bin`).

**Comment by hpsaturn** [comment]
yes, when you use Platformio you only needs loading in the server the firmware.bin, and no more, this file contains all, the firmware and the partitions info. I don't know how is it called with Arduino IDE
