### ISSUE TITLE
Does this library work with esp8266?

### ISSUE THREAD

**Issue by ateker01** [chrisjoyce911/esp32FOTA#81]
Hello 
Does this library work for esp8266? 
I tried the https.ino example but complier fails to find the SPIFFS header and shows "_fatal error: SPIFFS.h: No such file or directory_" so I wonder if it is because I use a 8266. 

Thanks in advance

**Comment by marcelstoer** [comment]
Consistent with its name and https://github.com/chrisjoyce911/esp32FOTA/blob/master/platformio.ini#L21 it only supports ESP32.
